# -*- coding: utf-8 -*-
"""assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11z0uf6-OACH28M1z3B1Ts2p7bJRAKCpl
"""

print('hello')

a = 2
a

a = 2
b = 3
print('a = '+str(a)+' and '+'b = '+str(b))

type(a)

s1 = 'RJ college'
type(s1)

f=2.34546796547
type(f)

a=[1,2,3]
a

type(a)

b=[4,5,6]
b

c = []
for i in range(len(a)):
  c.append(a[i]*b[i])
c

c = []
for i in range(len(a)):
  c.append(a[i]+b[i])
c

import time
print('sleeping')
time.sleep(30)
print('done sleeping')

import numpy as np
a=np.arange(15).reshape(3,5)
a

a.ndim

a.dtype

a.dtype.name

a.itemsize

a.size

type(a)

b=np.array([[11,13,14],[56,57,58]])
b

b.reshape(3,2)
b

c=b.reshape(3,2)
c

d=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
d

e=d.reshape(2,5)
e